### ISSUE TITLE
consider adding/creating one for git-annex or/and DataLad 

### ISSUE THREAD

**Issue by yarikoptic** [katrinleinweber/Git-for-bio-scientists#1]
;-)
some pointers: http://www.reproducibleimaging.org/module-reproducible-basics/02-vcs/#git-annex

**Comment by katrinleinweber** [comment]
Hi! I am planning to review your [FAIR Data lesson](http://www.reproducibleimaging.org/module-FAIR-data/) for a workshop. Thanks for that one :-)   But `git-annex`... I tried it superficially a few years ago, then didn't have a use-case anymore, and by now see `git-lfs` as the more popular solution. What do you think?

**Comment by yarikoptic** [comment]
FAIR Data:  great!  if you have any recommendations or fixes, do not hesitate to contribute: https://github.com/ReproNim/module-FAIR-data

`git-annex` vs `git-lfs`: my opinion might be biased, since I am one of the DataLad developers where we build on top of git-annex, and I have only superficial experience with `git-lfs`.  But here you go:  `git-annex` is more like a swiss-army knife for managing data within git.  It doesn't limit you to a specific server -- you could link or upload data to any other git clone of the repository (well, if there is also git-annex cmdline available on the other side, so can't be done for github), you could link to urls for files on the web, you could even "link" data files to the content of tar/zip-archives (that is what we do in datalad where public datasets come only in shape of those archives), you could upload your data files to "git-annex special remotes" anywhere with optional encryption etc.  AFAIK: `git-lfs` is more of a "one trick pony" solution -- you need a git-lfs server where you host your data files and interact with it to upload/download.  It works for centralized solutions, such as github, but it limits its utility big ways: I cannot just manage data files among my own personal clones of a git repository, I cannot easily make use of public/institutional hosting to host my repositories with data (like we do on http://datasets.datalad.org), I cannot just "link" to data available online elsewhere -- I would need to upload it first to the git-lfs server.
There is also a technical shortcoming: `git-lfs` AFAIK works via git smudge filters -- so for big files it needs first to analyze their content first to even say if things have changed or not.  git-annex version mode 6 is an attempt to go the same direction (primarily to work better on systems (Windows) with crippled filesystems (FAT)) but there are some shortcomings with this approach which would still need work at git level to make it work smoother.  git-annex's approach with symbolic links to content works smoothly/efficiently and non-ambiguously in majority of the cases.
With those differences in mind, and that you need to pay for any adequate size allowance for git-lfs on github, I do not actually know yet anyone using git-lfs in my domain (neuroimaging), and I feel that user-base of git-annex is growing here.  E.g. all our neuroimaging data collected at DBIC is placed under git-annex control (see https://github.com/repronim/reproin for more pointers), etc.

Hope this helps ;)  And please feel welcome to correct me if I misrepresented `git-lfs` anyhow

**Comment by katrinleinweber** [comment]
In that case, are you aware of https://github.com/mpg-age-bioinformatics/bit?

**Comment by yarikoptic** [comment]
Nope, didn't see that one yet. Thanks!
There is a number of solutions now which fill this niche of maintaining code and data under VCS, the same what git annex already does, and which it does to greater and wider extent I think. Some also add some additional unique features.
Here is some more examples https://github.com/dataversioncontrol/dvc, https://quiltdata.com

**Comment by katrinleinweber** [comment]
In all the above cases, improving the official docu seems more useful to me than creating a separate, unofficial guide/lesson.
